apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/mocdaniel/dod-amsterdam-examples
    targetRevision: HEAD
    path: apps
  syncPolicy:
    automated: {}
